# Generated by Django 5.0.1 on 2026-06-11 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('scientific_name', models.CharField(max_length=100)),
                ('water_type', models.CharField(max_length=20)),
                ('bioload', models.FloatField()),
                ('tags', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aquarium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('water_type', models.CharField(max_length=20)),
                ('volume', models.FloatField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aquariums', to=settings.AUTH_USER_MODEL)),
                ('species', models.ManyToManyField(related_name='aquariums', to='api.species')),
            ],
        ),
    ]
